### ISSUE TITLE
32b and 16b numeric specifications cause Unknown Token error

### ISSUE THREAD

**Issue by tomcircuit** [cstrotm/spl-6502#1]
I have observed that spl.py* throws an Unknown Token error when a numeric constant is specified to be 16b or 32b using the "%" and "#" characters, respectively:

```
( test 0 )
: main 
  0x1234#   
  0x7ff0 d!
  { }
;
```
C:\Users\lemenset\Personal\SPL\spl-6502>python spl.py test0 -t asm
Traceback (most recent call last):
  File "C:\Users\lemenset\Personal\SPL\spl-6502\spl.py", line 2166, in <module>
    app = SPLCompiler()
  File "C:\Users\lemenset\Personal\SPL\spl-6502\spl.py", line 2161, in __init__
    self.Compile()
  File "C:\Users\lemenset\Personal\SPL\spl-6502\spl.py", line 2126, in Compile
    self.CompileFunctions()       #  Generate assembly code for all functions
  File "C:\Users\lemenset\Personal\SPL\spl-6502\spl.py", line 1614, in CompileFunctions
    self.Error("Unknown token: " + str(token) + ", function = " + f)
  File "C:\Users\lemenset\Personal\SPL\spl-6502\spl.py", line 695, in Error
    raise ValueError("In " + self.funcName + " : " + self.Token + " : " + str(msg))
ValueError: In main : 0x1234# : Unknown token: 0x1234#, function = main

*Important note: I converted spl.py to Python 3 using "2to3" and some minor hand-edits. This error could be a consequence of the conversion, e.g. a difference in Python 3 vs. 2 string support.

**Comment by cstrotm** [comment]
Hi Tom,

thanks for the bug report. 

I've never used the 32b and 16b numeric specifiers, so I've never encountered this error.

I will look into this in the next days and create a patch / fix.
